name: Auto-generate index.html

on:
  push:
    branches:
      - main
    paths:
      - '**.html'
      - 'generate-index.sh'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x generate-index.sh

      - name: Run index generation script
        run: ./generate-index.sh

      - name: Commit and push index.html
        run: |
          git add index.html
          git diff --cached --quiet || git commit -m "Auto-update index.html"
          git push
